sudo: require
language: cpp

branches:
  only:
    - master

common_sources: &all_sources
  - ubuntu-toolchain-r-test
  - llvm-toolchain-xenial-6.0

env:
  global:
    - CODECOV_TOKEN="e3f86b6b-0770-4816-9b7d-19b0c550229f"


cache:
  - ccache
  - apt: true
  - directories:
    - ${TRAVIS_BUILD_DIR}/build/external

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      addons: &gcc7
        apt:
          sources: *all_sources
          packages:
            - g++-7
            - lcov
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && COVERAGE=Off"
    - os: linux
      dist: xenial
      compiler: gcc
      addons: &gcc7
        apt:
          sources: *all_sources
          packages: ['g++-7']
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && PISA_COMPILE_HEADERS=On"
    - os: linux
      dist: xenial
      compiler: gcc
      addons: &gcc8
        apt:
          sources: *all_sources
          packages: ['g++-8']
      env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8 && COVERAGE=Off && DOCKER=On"
    - os: linux
      dist: xenial
      compiler: gcc
      addons: &gcc9
        apt:
          sources: *all_sources
          packages: ['g++-9']
      env: MATRIX_EVAL="CC=gcc-9 && CXX=g++-9 && COVERAGE=Off && DOCKER=Off && TEST_CLI=On"
    - os: linux
      dist: xenial
      compiler: clang
      addons:
          apt:
              sources: *all_sources
              packages: ['clang-5.0', 'libstdc++-7-dev']
      env: MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0 && COVERAGE=Off"
    - os: linux
      dist: xenial
      compiler: clang
      addons:
          apt:
              sources: *all_sources
              packages: ['clang-6.0', 'libstdc++-7-dev']
      env: MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0 && COVERAGE=Off"
    - os: linux
      dist: xenial
      compiler: clang
      addons:
          apt:
              sources:
                - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
                  key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
              packages:
                - clang-format-9
      env: MATRIX_EVAL="COVERAGE=Off && CLANG_FORMAT=On"
    - os: linux
      dist: xenial
      compiler: clang
      addons:
          apt:
              sources:
                - ubuntu-toolchain-r-test
                - llvm-toolchain-xenial-6.0
                - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
                  key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
              packages:
                - ['clang-tidy-9', 'clang-9', 'libstdc++-7-dev']
      env: MATRIX_EVAL="CC=clang-9 && CXX=clang++-9 && COVERAGE=Off && TIDY=On"
    - os: osx
      osx_image: xcode10.3
      compiler: clang
      env: MATRIX_EVAL="CC=clang && CXX=clang++ && COVERAGE=Off"
    - os: osx
      osx_image: xcode11.2
      compiler: clang
      env: MATRIX_EVAL="CC=clang && CXX=clang++ && COVERAGE=Off"

# Install dependencies
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install ccache;
      export PATH="/usr/local/opt/ccache/libexec:$PATH";
    fi
  - if [[ "$TEST_CLI" == "On" ]]; then
      git clone https://github.com/sstephenson/bats.git;
      cd bats;
      sudo ./install.sh /usr/local;
    fi
  - eval "${MATRIX_EVAL}"
  
script:
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=${COVERAGE} -DPISA_COMPILE_HEADERS=${PISA_COMPILE_HEADERS} -DPISA_ENABLE_CLANG_TIDY=${TIDY} -DPISA_CLANG_TIDY_EXECUTABLE=clang-tidy-9 ${CMAKE_OPTIONS} ..
    - if [[ "$PISA_COMPILE_HEADERS" != "On" && "$CLANG_FORMAT" != "On" ]]; then
        make -j2;
        if [[ "$TIDY" != "On" ]]; then
            CTEST_OUTPUT_ON_FAILURE=TRUE ctest -j2;
            if [[ "$TEST_CLI" == "On" ]]; then
                bash ../test/cli/run.sh;
            fi
        fi
      fi
    - if [[ "$CLANG_FORMAT" == "On" ]]; then
        cd ..;
        wget https://raw.githubusercontent.com/Sarcasm/run-clang-format/master/run-clang-format.py;
        python run-clang-format.py --clang-format-executable clang-format-9 -r src/**/*.cpp include/pisa/**/*.hpp tools/*.cpp tools/*.hpp test/*.cpp;
      fi

after_success:
  - |-
    if [[ "${COVERAGE}" == "On" ]]; then
      bash <(curl -s https://codecov.io/bash);
    fi
  - |-
    if [[ "$TRAVIS_BRANCH" == "master" && "${DOCKER}" == "On" ]]; then
      curl -s -X POST \
      -H "Content-Type:application/json" \
      -H "Travis-API-Version:3" \
      -H "Accept:application/json" \
      -H "Authorization:token ${TRAVIS_API_TOKEN}" \
      -d '{"request":{"branch":"master"}}' \
      'https://api.travis-ci.com/repo/pisa-engine%2Fdocker/requests'
    fi


