name: Docker
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger docker build
      shell: bash	
      working-directory: ${{runner.workspace}}/build	
      run: |
            curl -s -X POST \
            -H "Content-Type:application/json" \
            -H "Travis-API-Version:3" \
            -H "Accept:application/json" \
            -H "Authorization:token ${{secrets.TRAVIS_API_TOKEN}}" \
            -d '{"request":{"branch":"master"}}' \
            'https://api.travis-ci.com/repo/pisa-engine%2Fdocker/requests'
